get http://localhost:3000/user-api/apps

###
get http://localhost:3000/user-api/apps/2

###
post http://localhost:3000/user-api/app
Content-Type: application/json

{
    "id":4,
    "name":"WhatsApp",
    "owner":"Meta"
}

###
put http://localhost:3000/user-api/app
Content-Type: application/json

{
    "id":3,
    "name":"FaceBook",
    "owner":"Meta"
}

###
delete http://localhost:3000/user-api/apps/3